'use strict';

const { channelViewModels } = require('./client');
const { groupChannels } = require('../../channel-groups');

/**
 * Emits pyproject.toml, Makefile, .gitignore and README.md for the generated project.
 *
 * @param {{ channels: Array<object>, protoPackages: Map<string, Map> }} model
 * @param {{ projectName: string, specTitle: string }} ctx
 * @returns {Array<{ path: string, content: string }>}
 */
function buildScaffoldFiles(model, ctx) {
  return [
    { path: 'pyproject.toml', content: pyprojectToml(ctx.projectName, ctx.specTitle) },
    { path: 'Makefile', content: makefile(ctx.projectName) },
    { path: '.gitignore', content: gitignore() },
    { path: 'README.md', content: readme(model, ctx) },
  ];
}

function pyprojectToml(projectName, specTitle) {
  const distName = projectName.replace(/_/g, '-');
  return `[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "${distName}"
version = "0.1.0"
description = "Generated MQTT message-bus client for ${specTitle}"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "paho-mqtt>=1.6,<3",
  "protobuf>=4.25,<6",
]

[project.optional-dependencies]
dev = [
  "grpcio-tools>=1.60",
  "pytest>=7.4",
]

[tool.hatch.build.targets.wheel]
packages = ["src/${projectName}"]
`;
}

function makefile(projectName) {
  return `.PHONY: proto install dev test clean

PYTHON ?= python3

# Compiles proto/${projectName}/*.proto into src/${projectName}/*_pb2.py (+ .pyi stubs).
# proto/ is the canonical source; the generated modules are build artifacts (gitignored).
proto:
\t$(PYTHON) -m grpc_tools.protoc \\
\t\t-I proto \\
\t\t--python_out=src \\
\t\t--pyi_out=src \\
\t\tproto/${projectName}/*.proto

install:
\t$(PYTHON) -m pip install -e .

dev:
\t$(PYTHON) -m pip install -e ".[dev]"

test: dev proto
\t$(PYTHON) -m pytest

clean:
\trm -rf src/${projectName}/*_pb2.py src/${projectName}/*_pb2.pyi
\tfind . -type d -name "__pycache__" -exec rm -rf {} +
\trm -rf .pytest_cache *.egg-info dist build
`;
}

function gitignore() {
  return `__pycache__/
*.py[cod]
.venv/
venv/
*.egg-info/
dist/
build/
.pytest_cache/
.mypy_cache/

# Generated by \`make proto\` — proto/ is the canonical source
*_pb2.py
*_pb2.pyi
`;
}

function readme(model, ctx) {
  const { projectName, specTitle } = ctx;
  const channels = channelViewModels(model.channels);
  const { flat, groups } = groupChannels(channels, (c) => c.attrName);
  const example = groups[0] ? groups[0].channels[0] : flat[0];
  const protoFiles = [...model.protoPackages.keys()]
    .map((pkg) => `proto/${projectName}/${pkg.split('.').pop()}.proto`)
    .sort();

  const exampleAttr = groups[0]
    ? `${groups[0].name}.${groups[0].channels[0].attrName}`
    : example
      ? example.attrName
      : 'some_channel';
  const exampleType = example ? example.typeRef : 'YourMessageType';
  const exampleAddress = example ? example.address : 'your/topic';

  return `# ${projectName}

Python MQTT client generated from **${specTitle}** by [asyncapi-mqtt-proto-gen](https://github.com/melalex/asyncapi-mqtt-proto-gen) \\
(\`asyncapi generate fromTemplate <spec>.yaml <this-generator> -p lang=python -p projectName=${projectName}\`).

Every channel in the spec becomes a typed \`Channel\` on \`${projectName}.MessageBus\`. A channel that
carries AsyncAPI tags is nested under each tag (slugified) — \`message_bus.<tag>.<channel>\`; a
channel with no tags stays top-level — \`message_bus.<channel>\`. Multi-tag channels appear under each.

\`\`\`python
from ${projectName} import MessageBus, MqttConfig
from ${projectName} import ${example ? example.moduleAlias : 'some_module_pb2'}

message_bus = MessageBus(MqttConfig(host="localhost"))
message_bus.connect()

message_bus.${exampleAttr}.subscribe(lambda msg: handle(msg))

msg = ${exampleType}()
message_bus.${exampleAttr}.publish(msg)

message_bus.${exampleAttr}.address  # "${exampleAddress}"
\`\`\`

\`publish\`/\`subscribe\` always use protobuf binary encoding (\`SerializeToString\`/\`ParseFromString\`).

## Project layout

\`\`\`
proto/${projectName}/        Generated .proto files (one per proto package) — canonical source of truth
src/${projectName}/          __init__.py, client.py, and *_pb2.py/*_pb2.pyi generated by \`make proto\`
tests/                        pytest tests using an in-memory MQTT transport (no broker required)
\`\`\`

Generated proto files: ${protoFiles.map((f) => `\`${f}\``).join(', ')}.

## Building

Prerequisites: Python \\>= 3.9.

\`\`\`sh
make dev     # pip install -e ".[dev]" — installs the package plus grpcio-tools and pytest
make proto   # compiles proto/${projectName}/*.proto -> src/${projectName}/*_pb2.py
make test    # runs dev + proto, then pytest
\`\`\`

\`make proto\` must be re-run whenever \`proto/${projectName}/*.proto\` changes; the generated
\`*_pb2.py\`/\`*_pb2.pyi\` files are build artifacts (gitignored), not checked in.
`;
}

module.exports = { buildScaffoldFiles };
